#!/usr/bin/env bash

_buku () {
    buku --nostdin "$@"
}

_rofi () {
    rofi -dmenu -i -no-sort -theme-str 'mainbox { padding: 25% 5%;}' "$@"
}

# display settings
display_type=1
max_str_width=80

# Keyboard shortcuts
: ${KB_SWITCH_VIEW="Alt+Tab"}
: ${KB_NEW_BOOKMARK="Alt+n"}
: ${KB_ACTIONS="Alt+a"}
: ${KB_EDIT="Alt+e"}
: ${KB_DELETE="Alt+d"}

# colors
help_color="#FF00AA"
# sources global and local config if those exist
source_buku_config(){
 [[ -f /etc/buku_run.config ]] && source /etc/buku_run.config

 XDG_CONFIG_DIR=${XDG_CONFIG_DIR:-$HOME/.config}

 [[ -f $XDG_CONFIG_DIR/buku_run/config ]] &&\
   source $XDG_CONFIG_DIR/buku_run/config ||\
   echo "User config file \'~/.config/buku_run/config\' not found. using global config"
}

on_bookmarks_enter(){
  # select whether to open the bookmark or just type it
  xdotool type --clearmodifiers -- "$(get_url_from_id $1)"
}

main () {

    HELP="Welcome to Buku | Use <span color='${help_color}'>${KB_NEW_BOOKMARK}</span> to add a new Bookmark | Use <span color='${help_color}'>${KB_SWITCH_VIEW}</span> to switch View. | Use <span color='${help_color}'>${KB_ACTIONS}</span> for actions"

    if [[ $mode == "bookmarks" ]]; then
        content=$(parse_buku)
        menu=$(echo "${content}" | _rofi -p 'Bookmark' -filter "${filter}" -mesg "${HELP}" -kb-custom-1 "${KB_NEW_BOOKMARK}" -kb-custom-2 "${KB_SWITCH_VIEW}" -kb-custom-3 "${KB_ACTIONS}" -kb-custom-4 "${KB_EDIT}" -kb-custom-5 "${KB_DELETE}")
    elif [[ $mode == "tags" ]]; then
        menu=$(_buku --np --st | awk '{$NF=""; print $0}' | cut -d ' ' -f2-  | _rofi -p '> ' -mesg "${HELP}" -kb-custom-1 "${KB_NEW_BOOKMARK}" -kb-custom-2 "${KB_SWITCH_VIEW}" -kb-custom-3 "${KB_ACTIONS}" -kb-custom-4 "${KB_EDIT}" -kb-custom-5 "${KB_DELETE}")
    fi

    val=$?
    case $val in
        1) exit ;;
        12) options_menu ;;
        10) add_mark ;;
        14) delete_menu ;;
        13) edit_menu ;;
        11)
            if [[ $mode =~ (bookmarks|tags) ]]; then
                export mode=$( [[ $mode == "bookmarks" ]] && echo "tags" || echo "bookmarks" )
                mode=$mode main
            fi
            ;;
        0)
            if [[ $mode == "bookmarks" ]]; then
                id=$(get_id "$content" "$menu")
                for bm in ${id}; do
                  on_bookmarks_enter $bm
                done
            elif [[ $mode == "tags" ]]; then
                filter="${menu}" mode="bookmarks" main
            fi
            ;;
    esac
}

options_menu () {
  case $mode in
    bookmarks)
        askmenu=$(echo -e "< Return\n---\n1. Edit\n2. Delete" | _rofi -p '> ' -mesg "Choose Action for bookmark")
        val=$?
        [[ $val -eq 1 ]] && exit
        [[ $val -ne 0 ]] && exit

        [[ "$askmenu" == "< Return" ]] && { export mode=bookmarks;main; }
        [[ "$askmenu" == "1. Edit" ]] && { edit_menu; }
        [[ "$askmenu" == "2. Delete" ]] && { delete_menu; }
    ;;
    tags)
        askmenu=$(echo -e "< Return\n---\n1. Replace Tag\n2. Delete Tag" | _rofi -p '> ' -mesg "Choose Action for tag \"${menu}\"")
        val=$?

        [[ $val -eq 1 ]] && exit
        [[ $val -ne 0 ]] && exit

        [[ $askmenu == "< Return" ]] && export mode=tags;main

        case $askmenu in
        "1. Replace Tag")
            newtag=$(echo | _rofi -p '> ' -mesg "Enter new tag name for tag \"${menu}\"")
            val=$?
            [[ $val -eq 1 ]] && exit
            [[ $val -ne 0 ]] && exit

            [[ $newtag == "" ]] &&\
               mode=tags main ||\
               _buku -r "${menu}" "${newtag}";mode=tags main
            ;;
          "2. Delete Tag")
            delask=$(echo -e "1. Yes\n2. No" | _rofi -p '> ' -mesg "Really delete tag?")
            val=$?
            [[ $val -eq 1 ]] && exit
            [[ $val -ne 0 ]] && exit

            [[ $delask == "1. Yes" ]] &&\
               _buku -r "${menu}";mode=tags main ||\
               mode=tags main
            ;;
        esac
    ;;
  esac
}

delete_menu () {
    id=$(get_id "$content" "$menu")
    delask=$(echo -e "1. Yes\n2. No" | _rofi -p '> ' -mesg "Really delete bookmark?")
    val=$?
    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 0 ]]; then
        if [[ $delask == "1. Yes" ]]; then
            _buku -d ${id} --tacit
            mode=bookmarks main
        elif [[ $delask == "2. No" ]]; then
            options_menu
        fi
    fi
}

edit_menu () {
    id=$(get_id "$content" "$menu")
    title="$(get_title_from_id $id)"
    bookmark="$(get_url_from_id $id)"
    tags="$(get_tags_from_id $id)"
    content=$(echo -e "1. title: $title\n2. url: $bookmark\n3. tags: $tags")
    editmenu=$(echo -e "< Return\n---\n${content}" | _rofi -p '> ')
    val=$?
    [[ $val -eq 1 ]] && exit
    [[ $val -ne 0 ]] && exit

    case $editmenu in
      "< Return")
        main
        ;;
      "tags: NOTAG")
        add_tags --update
        ;;
      3\.\ tags:*)
        tags="${tags}" edit_tags
        ;;
      2\.\ url:*)
        edit_bookmark
        ;;
      1\.\ title:*)
        edit_title
        ;;
      *)
        ;;
    esac
}

edit_tags () {
    edittagsmenu=$(echo | _rofi -filter "${tags}" -p '> ' -mesg "Edit Tags and hit Enter")
    val=$?
    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 0 ]]; then
        _buku -u ${id} --tag "${edittagsmenu}"
    fi
    mode=bookmarks main
}

edit_bookmark () {
    bmarkmenu=$(echo "" | _rofi -p "> " -filter "${bookmark}" -mesg "Edit Bookmark and hit Enter")
    val=$?
    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 0 ]]; then
        if [[ $bmarkmenu == "http"* ]]; then
            _buku -u "${id}" --url "${bmarkmenu}"
        else
            echo "" | rofi -e "Not a valid URI, Make sure URLs start with http"
            edit_bookmark
        fi
    fi
    mode=bookmarks main
}

edit_title () {
  titlemenu=$(echo "" | _rofi -p "> " -filter "${title}" -mesg "Edit Title and hit Enter")
  val=$?
  if [[ $val -eq 1 ]]; then
    exit
  elif [[ $val -eq 0 ]]; then
    _buku -u "${id}" --title "${titlemenu}"
  fi
  mode=bookmarks main
}

add_mark () {
    inserturl=$(echo -e "$(xclip -o)" | _rofi -p '> ' -mesg "Use URL below or type manually")
    val=$?
    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 0 ]]; then
        add_tags
    fi
}

add_tags () {
    inserttags=$(_buku --np --st | awk '{$NF=""; print $0}' | cut -d ' ' -f2- | _rofi -p '> ' -mesg "Add some tags. Separate tags with ', '")
    val=$?
    if [[ $val -eq 1 ]]; then
        exit
    elif [[ $val -eq 0 ]]; then
        if [[ $(echo "${inserttags}" | wc -l) -gt 1 ]]; then
            taglist=$(echo "${inserttags}" | tr '\n' ',')
            tags=()
            for tag in $taglist; do
                tags+=("$tag")
            done
        else
            tags=${inserttags}
        fi
        if [[ $1 == "--update" ]]; then
            _buku -u "${id}" --tag ${tags}
        else
            _buku -a ${inserturl} ${tags}
        fi
    fi
}

parse_buku () {
  _buku --nc -p -j 2>/dev/null | jq -r '.[] | "\(.index)	\(if .uri | length <= 80 then .uri else .uri[:80] + "..." end)	\(.title)	\(.tags | select(. != "") // "NOTAGS")"' | column -s $'	' -t
}

get_id () {
  id=$(echo "${2%% *}")
  if [ -z "$id" ]; then
    prev=""
    IFS=$'\n'
    for line in $1; do
      if [ "$2" = "$line" ]; then
        id=$(echo "${prev%% *}")
        break
      else
        prev="$line"
      fi
    done
  fi
  echo $id
}

get_title_from_id () {
  echo "$(_buku --nc -p $1 -f 30)"
}

get_url_from_id () {
  echo "$(_buku --nc -p $1 -f 10)"
}

get_tags_from_id () {
  echo "$(_buku --nc -p $1 -j | jq -r .tags)"
}

source_buku_config
mode=bookmarks main
